name: Release

on:
  push:
    tags:
      - 'v*'  # 只在 push v开头的 tag 时触发

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: python training/train.py

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/diabetes-api:${GITHUB_REF_NAME}
          docker build -t $IMAGE_NAME .

      - name: Test container
        run: |
          docker run -d -p 8000:8000 --name test_container $IMAGE_NAME
          for i in {1..10}; do
            sleep 2
            if curl -f http://localhost:8000/health; then
              echo "Service is up!"
              break
            fi
          done
          docker logs test_container
          docker stop test_container
          docker rm test_container

      - name: Push Docker image
        run: |
          echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          docker push $IMAGE_NAME

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}